// swift-tools-version: 5.9
import PackageDescription

// AUTO-GENERATED by KLightMapper-src CI — do not edit by hand.
// Binary release of the KLightMapper camera-based light-mapping
// framework. Source lives in the private KLightMapper-src repo;
// only the prebuilt XCFramework is published here.
//
// version:    v1.4.1
// source sha: f835f314776404f44d5bd4fe836b1360892e8bdd
let package = Package(
    name: "KLightMapper",
    // iOS 17 floor matches the source package. macOS 13 floor lets
    // the offline analyzer + xmodel writer link on Macs that haven't
    // upgraded to 14 yet; the scan-capture entry points
    // ( on macOS) are 
    // because Continuity Camera + 
    // both require macOS 14.
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [
        .library(name: "KLightMapper", targets: ["KLightMapper"]),
    ],
    targets: [
        .binaryTarget(
            name: "KLightMapper",
            url: "https://github.com/KulpLights/KLightMapper/releases/download/v1.4.1/KLightMapper.xcframework.zip",
            checksum: "a7f2d0683a07bbc693181ae155c51c96fdef7c85064957d4e5508757cae1294e"
        ),
    ]
)
