// swift-tools-version: 5.9
import PackageDescription

// AUTO-GENERATED by KLightMapper-src CI — do not edit by hand.
// Binary release of the KLightMapper camera-based light-mapping
// framework. Source lives in the private KLightMapper-src repo;
// only the prebuilt XCFramework is published here.
//
// version:    v1.1.0
// source sha: e4f20abe940cd0f0b65b74d7f0e7d99a78a90b9d
let package = Package(
    name: "KLightMapper",
    // iOS 17 floor matches the source package. macOS 13 floor lets
    // the offline analyzer + xmodel writer link on Macs that haven't
    // upgraded to 14 yet; the scan-capture entry points
    // ( on macOS) are 
    // because Continuity Camera + 
    // both require macOS 14.
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [
        .library(name: "KLightMapper", targets: ["KLightMapper"]),
    ],
    targets: [
        .binaryTarget(
            name: "KLightMapper",
            url: "https://github.com/KulpLights/KLightMapper/releases/download/v1.1.0/KLightMapper.xcframework.zip",
            checksum: "f71bb8a25c42b8481d825c2a2d3fb2d32b5accbd80b33705208ed9c6d9a0e26a"
        ),
    ]
)
