// swift-tools-version: 5.9
import PackageDescription

// AUTO-GENERATED by KLightMapper-src CI — do not edit by hand.
// Binary release of the KLightMapper camera-based light-mapping
// framework. Source lives in the private KLightMapper-src repo;
// only the prebuilt XCFramework is published here.
//
// version:    latest
// source sha: 4e8dd3d79d4c85ff1c017c633df3f1accfb9289b
let package = Package(
    name: "KLightMapper",
    // iOS 17 floor matches the source package. macOS 13 floor lets
    // the offline analyzer + xmodel writer link on Macs that haven't
    // upgraded to 14 yet; the scan-capture entry points
    // ( on macOS) are 
    // because Continuity Camera + 
    // both require macOS 14.
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [
        .library(name: "KLightMapper", targets: ["KLightMapper"]),
    ],
    targets: [
        .binaryTarget(
            name: "KLightMapper",
            url: "https://github.com/KulpLights/KLightMapper/releases/download/latest-build/KLightMapper.xcframework.zip",
            checksum: "4187ceca321429991803e56c8e6d7c4636e915eb212db46153b27eb035721c3d"
        ),
    ]
)
